DROP SCHEMA bci_db IF EXISTS;
CREATE SCHEMA bci_db;

DROP TABLE "phones" IF EXISTS;
CREATE TABLE "phones"(
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "city_code" INTEGER,
    "country_code" INTEGER,
    "number" INTEGER,
    "user_id" UUID
);
ALTER TABLE "phones" ADD CONSTRAINT "pk_id_phone" PRIMARY KEY("id");

DROP TABLE "users" IF EXISTS;
CREATE TABLE "users"(
    "id" UUID DEFAULT RANDOM_UUID() NOT NULL,
    "is_active" BOOLEAN,
    "created" TIMESTAMP(6) WITH TIME ZONE,
    "last_login" TIMESTAMP(6) WITH TIME ZONE,
    "modified" TIMESTAMP(6) WITH TIME ZONE,
    "token" CHARACTER VARYING(255),
    "email" CHARACTER VARYING(100) NOT NULL UNIQUE,
    "name" CHARACTER VARYING(100) NOT NULL UNIQUE,
    "password" CHARACTER VARYING(255)
--    constraint email_key unique ("email")
);

ALTER TABLE "users" ADD CONSTRAINT "pk_id_user" PRIMARY KEY("id");

ALTER TABLE "phones" ADD CONSTRAINT "fk_user_id" FOREIGN KEY("user_id") REFERENCES "users"("id") NOCHECK;
